import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            // needed for netlayer packages
            url = 'https://jitpack.io'
            content {
                includeGroup('com.github.bisq-network.netlayer')
                includeGroup('com.github.bisq-network.tor-binary')
                includeGroup('com.github.bisq-network')
            }
        }
        mavenCentral()
        mavenLocal {
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

rootProject.name = 'ngtor'

include 'ngtor:ngtor-app'
