app.name: ngtor-dev
app.description: Easy, simple and instant Onion URLs to your localhost server.
app.home: '${user.home}/.ngtor-dev'

spring.application.name: '${app.name}'
spring.http.log-request-details: false

#debug: true
spring.devtools.add-properties: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.name: '${app.home}/${app.name}.log'
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG
